version: "3"

services:
  app:
    build:
      context: https://github.com/cu-webteam/d8-platform.git
      args:
        USER_IP: X.X.X.X
        TEST_BASE_URI: http://alliance.test-creighton.acsitefactory.com/
        TEST_PATH: /tests
    image: d8-platform/docroot
    container_name: creighton.app
    ports:
      - "8088:80"
    volumes:
      - ./config:/var/www/creighton

  mail:
    image: mailhog/mailhog:latest
    container_name: drupal.mail

  testdb:
    image: mysql:5.7
    container_name: drupal.test.db
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "8306:3306"

  hub:
    image: selenium/hub:latest
    container_name: selenium.hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:latest
    container_name: selenium.chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub

  firefox:
    image: selenium/node-firefox-debug:latest
    container_name: selenium.firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub